#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
SOURCE = Path(__file__).resolve().with_name("schema_manifest.json")
TARGET = ROOT / "dashboard" / "frontend" / "src" / "lib" / "generatedNlSchemaManifest.ts"


def main() -> None:
    manifest = json.loads(SOURCE.read_text(encoding="utf-8"))
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    output = (
        "// Code generated by dashboard/backend/nlauthor/catalog/generate_frontend_catalog.py.\n"
        "// DO NOT EDIT.\n\n"
        "export const GENERATED_NL_SCHEMA_MANIFEST = "
        + payload
        + " as const;\n"
    )
    TARGET.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
